---

- name: mnn.nginx
  src: https://github.com/MotherNatureNetwork/ansible-nginx.git
  version: v1.0.1

- name: theonion.uwsgi-emperor
  src: https://github.com/MotherNatureNetwork/ansible-uwsgi-emperor
